version: "3.8"
services:
  api4:
    container_name: api4
    build:
      dockerfile: Dockerfile
      context: "."
    image: spring-boot-playground:latest
    ports:
      - '8080:8080'
      - '35729:35729'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql4:3306/store?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    command: sh entrypoint-docker.sh
    volumes:
      - ./:/app/
    depends_on:
      - mysql4
    networks:
      - lab4-network
  mysql4:
    image: mysql:latest
    container_name: mysql4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - lab4-db:/var/lib/mysql
    networks:
      - lab4-network
volumes:
  lab4-db:
networks:
  lab4-network: